// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4_l2_uL4qjpU2wp-1FIkF9bbs5NF4xA',
    appId: '1:130059843669:web:9742c0a46832c57c0b3cdc',
    messagingSenderId: '130059843669',
    projectId: 'tracker-94041',
    authDomain: 'tracker-94041.firebaseapp.com',
    storageBucket: 'tracker-94041.firebasestorage.app',
    measurementId: 'G-LYF5VWW4T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmbiQcMYnI5VwKbol0_GUzwjp5q6eIr3g',
    appId: '1:130059843669:android:c394b63e0782f47d0b3cdc',
    messagingSenderId: '130059843669',
    projectId: 'tracker-94041',
    storageBucket: 'tracker-94041.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBITDP3pPkV8BchN-WvmFV3nPlw3E4Zymk',
    appId: '1:130059843669:ios:f50e8b9fafa7bf3c0b3cdc',
    messagingSenderId: '130059843669',
    projectId: 'tracker-94041',
    storageBucket: 'tracker-94041.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBITDP3pPkV8BchN-WvmFV3nPlw3E4Zymk',
    appId: '1:130059843669:ios:f50e8b9fafa7bf3c0b3cdc',
    messagingSenderId: '130059843669',
    projectId: 'tracker-94041',
    storageBucket: 'tracker-94041.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO4_l2_uL4qjpU2wp-1FIkF9bbs5NF4xA',
    appId: '1:130059843669:web:d5982248130e24b70b3cdc',
    messagingSenderId: '130059843669',
    projectId: 'tracker-94041',
    authDomain: 'tracker-94041.firebaseapp.com',
    storageBucket: 'tracker-94041.firebasestorage.app',
    measurementId: 'G-44LCVSZQEP',
  );

}